export const UnderlineTypes = Object.freeze({
  GREEN_LONG_UNDERLINE: "GREEN_LONG_UNDERLINE",
  GREEN_SHORT_UNDERLINE: "GREEN_SHORT_UNDERLINE",
  PURPLE_SHORT_UNDERLINE: "PURPLE_SHORT_UNDERLINE",
  WHITE_LONG_UNDERLINE: "WHITE_LONG_UNDERLINE",
  WHITE_CURLY_UNDERLINE: "WHITE_CURLY_UNDERLINE",
});
